# Generated by Django 5.2.1 on 2025-06-05 14:00

import time
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.FloatField(default=time.time)),
                ('transactions', models.JSONField(default=list)),
                ('previous_hash', models.CharField(max_length=64)),
                ('nonce', models.IntegerField(default=0)),
                ('current_hash', models.CharField(blank=True, max_length=64)),
                ('public_hash', models.CharField(blank=True, max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PendingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=100)),
                ('rice_amount', models.IntegerField()),
                ('production_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verifications', models.JSONField(default=list)),
            ],
        ),
    ]
