# Generated by Django 5.2.3 on 2025-06-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransaction',
            name='is_ready_for_block',
            field=models.BooleanField(default=False),
        ),
    ]
